name: test-all
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v1
    - name: Hello world action step
      uses: actions/hello-world-docker-action@v1

    - name: Do test
      run: docker run -it --rm test-docker-action:1.0 /do-test.sh





