name: test-all
on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - name: Build Docker Image
      run: docker build -t test-docker-action -f ./docker/Dockerfile . 

    - name: Do test
      run: |
        docker run -v `pwd`/src:/test \
		test-docker-action \
		/test/do-test.sh





